/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed-dim": "#b4c5ff",
        "primary": "#004ac6",
        "inverse-surface": "#2d3133",
        "on-tertiary": "#ffffff",
        "on-secondary-fixed": "#00174b",
        "on-error": "#ffffff",
        "on-primary-fixed-variant": "#003ea8",
        "outline-variant": "#c3c6d7",
        "on-surface": "#191c1e",
        "surface-tint": "#0053db",
        "on-primary-container": "#eeefff",
        "surface-container-lowest": "#ffffff",
        "surface-container-high": "#e6e8eb",
        "on-primary": "#ffffff",
        "on-secondary-fixed-variant": "#31447b",
        "secondary": "#495c95",
        "error-container": "#ffdad6",
        "surface-container": "#eceef1",
        "on-tertiary-fixed-variant": "#7d2d00",
        "surface-dim": "#d8dadd",
        "tertiary": "#943700",
        "surface": "#f7f9fc",
        "surface-container-low": "#f2f4f7",
        "inverse-primary": "#b4c5ff",
        "primary-container": "#2563eb",
        "primary-fixed": "#dbe1ff",
        "on-primary-fixed": "#00174b",
        "on-surface-variant": "#434655",
        "on-secondary": "#ffffff",
        "inverse-on-surface": "#eff1f4",
        "tertiary-container": "#bc4800",
        "error": "#ba1a1a",
        "surface-bright": "#f7f9fc",
        "on-tertiary-container": "#ffede6",
        "on-tertiary-fixed": "#360f00",
        "background": "#f7f9fc",
        "tertiary-fixed": "#ffdbcd",
        "secondary-container": "#acbfff",
        "on-error-container": "#93000a",
        "primary-fixed-dim": "#b4c5ff",
        "tertiary-fixed-dim": "#ffb596",
        "surface-variant": "#e0e3e6",
        "outline": "#737686",
        "surface-container-highest": "#e0e3e6",
        "on-background": "#191c1e",
        "on-secondary-container": "#394c84",
        "secondary-fixed": "#dbe1ff"
      },
      fontFamily: {
        "headline": ["Poppins", "sans-serif"],
        "body": ["Roboto", "sans-serif"],
        "label": ["Inter", "sans-serif"],
        "poppins": ["Poppins", "sans-serif"],
        "roboto": ["Roboto", "sans-serif"],
        "inter": ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.25rem",
        "lg": "0.5rem",
        "xl": "0.75rem",
        "full": "9999px"
      },
    },
  },
  plugins: [],
}
